services:
    postgres:
        image: postgres:15
        restart: always
        ports:
            - 3001:5432
        environment:
            - POSTGRES_USER=${POSTGRES_USER-username}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD-password}
        volumes:
            - postgres:/var/lib/postgresql/data
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready" ]
            interval: 1m30s
            timeout: 30s
            retries: 5
            start_period: 30s

volumes:
    postgres:
