services:
    pg:
        container_name: pg
        image: postgres:15
        restart: always
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
            interval: 10s
            retries: 5
            start_period: 30s
            timeout: 10s
        volumes:
            - pgdata:/var/lib/postgresql/data
        env_file:
            - .env
        environment:
            - POSTGRES_USER=${POSTGRES_USER?Variable POSTGRES_USER not set}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable POSTGRES_PASSWORD not set}
            - POSTGRES_DB=${POSTGRES_DB?Variable POSTGRES_DB not set}
            - LANG=en_US.UTF-8
            - LC_ALL=en_US.UTF-8
        ports:
            - 5432:5432

volumes:
    pgdata:
